# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the Python script and config.json file into the container at /app
COPY test.py /app/
COPY config_test.json /app/

# Run the Python script when the container launches
CMD ["python", "test.py"]

~                               
