FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY server1.py /app
COPY server2.py /app
COPY config.json /app

# Make ports available to the world outside this container
EXPOSE 5000
EXPOSE 6000
CMD ["python"]
