# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY Client1.py /app/
COPY config_2server_client.json /app/

# Make port 5000 available to the world outside this container
EXPOSE 5100

# Define environment variable
ENV NAME client1

# Run app.py when the container launches
CMD ["python", "Client1.py"]
~                              
