version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/testwork
    networks:
      - mynetwork

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/testwork
    networks:
      - mynetwork

networks:
  mynetwork:
